# /opt/lab-setup/configs/lab-config.conf

VARIANT="18"
USER_NAME="oshlakov"
GROUP_NAME="ia232"
DOMAIN="${USER_NAME}.${GROUP_NAME}.local"

LAN_SUBNET="192.168.${VARIANT}.0"
LAN_NETMASK="255.255.255.0"
LAN_CIDR="24"
UPSTREAM_DNS="8.8.8.8"

# Интерфейсы
WAN_IFACE="ens33"
LAN_IFACE="ens37" # Для gateway
SINGLE_IFACE="ens33" # Для внутренних серверов

# IP-адреса машин
GW_IP="192.168.${VARIANT}.1"
SEAFILE_IP="192.168.${VARIANT}.4"
MAIL_IP="192.168.${VARIANT}.5"
WP_IP="192.168.${VARIANT}.6"
PBIN_IP="192.168.${VARIANT}.7"

# Диапазон DHCP для клиентских ПК
DHCP_START="192.168.${VARIANT}.10"
DHCP_END="192.168.${VARIANT}.250"