version: '3.8'

services:
  ansible-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: ansible-server
    hostname: ansible-server
    tty: true

  client1:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client1
    hostname: client1

  client2:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client2
    hostname: client2